HYTV-174: Drupal 10 upgrade.
UniversityofHelsinki/Opetustila-esittely pull request #469
Opened 2023-09-20 08:56 UTC by deiviic

2023-09-26 06:08 UTC, misterjoonas commented on drupal/patches/d10_version_support.patch
> +diff --git a/translatable_menu_link_uri.info.yml b/translatable_menu_link_uri.info.yml
This module has D10 support now in 2.1.0 version https://www.drupal.org/project/translatable_menu_link_uri

2023-09-26 06:12 UTC, misterjoonas commented on drupal/patches/null_offset_fix.patch
> +diff --git a/core/modules/views/src/Plugin/views/query/QueryPluginBase.php b/core/modules/views/src/Plugin/views/query/QueryPluginBase.php
Why is this patch applied? Is there an issue to reference? If not then one could be created against Drupal core and patch provided there.

2023-09-26 06:14 UTC, misterjoonas commented on drupal/patches/null_offset_fix.patch
> +diff --git a/core/modules/views/src/Plugin/views/query/QueryPluginBase.php b/core/modules/views/src/Plugin/views/query/QueryPluginBase.php
Check this issue https://www.drupal.org/project/drupal/issues/3361177

2023-09-26 06:29 UTC, misterjoonas commented
There are a few updates available for contrib modules at https://opetustila-test.it.helsinki.fi/en/admin/reports/updates and Leaflet 10.0.16 seems to be unsupported.

2023-09-26 06:44 UTC, misterjoonas requested changes
A few more module updates and this should be good to go 👍

2023-10-02 06:43 UTC, deiviic commented
@misterjoonas Anything else requires changes?

2023-10-02 07:30 UTC, misterjoonas commented on drupal/patches/d10_version_support.patch
> +diff --git a/translatable_menu_link_uri.info.yml b/translatable_menu_link_uri.info.yml
I guess the this file can be removed?

2023-10-05 12:33 UTC, misterjoonas approved these changes

2023-10-06 07:16 UTC, merged